// <auto-generated />
using System;
using CA_FacultyDbCodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CA_FacultyDbCodeFirst.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20231120170012_DepartmentAndStudent")]
    partial class DepartmentAndStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.AcademicStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcademicStaffs");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Credit")
                        .HasColumnType("smallint");

                    b.Property<short>("Ects")
                        .HasColumnType("smallint");

                    b.Property<int>("NumberOfAcademicStaff")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStudent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.CourseAndAcademicStaff", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("AcademicStaffId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "AcademicStaffId");

                    b.HasIndex("AcademicStaffId");

                    b.ToTable("CourseAndAcademicStaff");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.CourseAndStudent", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseAndStudent");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfAcademicStaff")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStudent")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.DepartmentAndAcademicStaff", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("AcademicStaffId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "AcademicStaffId");

                    b.HasIndex("AcademicStaffId");

                    b.ToTable("DepartmentAndAcademicStaff");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.DepartmentAndStudent", b =>
                {
                    b.Property<int>("DeparmantId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("DeparmantId", "StudentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("DepartmentAndStudent");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.CourseAndAcademicStaff", b =>
                {
                    b.HasOne("CA_FacultyDbCodeFirst.Entities.AcademicStaff", "AcademicStaff")
                        .WithMany("CourseAndAcademicStaffs")
                        .HasForeignKey("AcademicStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_FacultyDbCodeFirst.Entities.Course", "Course")
                        .WithMany("CourseAndAcademicStaffs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicStaff");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.CourseAndStudent", b =>
                {
                    b.HasOne("CA_FacultyDbCodeFirst.Entities.Course", "Course")
                        .WithMany("CourseAndStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_FacultyDbCodeFirst.Entities.Student", "Student")
                        .WithMany("CourseAndStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.DepartmentAndAcademicStaff", b =>
                {
                    b.HasOne("CA_FacultyDbCodeFirst.Entities.AcademicStaff", "AcademicStaff")
                        .WithMany("DepartmentAndAcademicStaffs")
                        .HasForeignKey("AcademicStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_FacultyDbCodeFirst.Entities.Department", "Department")
                        .WithMany("DepartmentAndAcademicStaffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicStaff");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.DepartmentAndStudent", b =>
                {
                    b.HasOne("CA_FacultyDbCodeFirst.Entities.Department", "Department")
                        .WithMany("DepartmentAndStudents")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_FacultyDbCodeFirst.Entities.Student", "Student")
                        .WithMany("DepartmentAndStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.AcademicStaff", b =>
                {
                    b.Navigation("CourseAndAcademicStaffs");

                    b.Navigation("DepartmentAndAcademicStaffs");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.Course", b =>
                {
                    b.Navigation("CourseAndAcademicStaffs");

                    b.Navigation("CourseAndStudents");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.Department", b =>
                {
                    b.Navigation("DepartmentAndAcademicStaffs");

                    b.Navigation("DepartmentAndStudents");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.Student", b =>
                {
                    b.Navigation("CourseAndStudents");

                    b.Navigation("DepartmentAndStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
