// <auto-generated />
using System;
using CA_FacultyDbCodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CA_FacultyDbCodeFirst.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20231120162704_AcademicStaffAndDepartment")]
    partial class AcademicStaffAndDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.AcademicStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcademicStaff");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfAcademicStaff")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStudent")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.DepartmentAndAcademicStaff", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("AcademicStaffId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "AcademicStaffId");

                    b.HasIndex("AcademicStaffId");

                    b.ToTable("DepartmentAndAcademicStaff");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.DepartmentAndAcademicStaff", b =>
                {
                    b.HasOne("CA_FacultyDbCodeFirst.Entities.AcademicStaff", "AcademicStaff")
                        .WithMany("DepartmentAndAcademicStaffs")
                        .HasForeignKey("AcademicStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_FacultyDbCodeFirst.Entities.Department", "Department")
                        .WithMany("DepartmentAndAcademicStaffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicStaff");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.AcademicStaff", b =>
                {
                    b.Navigation("DepartmentAndAcademicStaffs");
                });

            modelBuilder.Entity("CA_FacultyDbCodeFirst.Entities.Department", b =>
                {
                    b.Navigation("DepartmentAndAcademicStaffs");
                });
#pragma warning restore 612, 618
        }
    }
}
